export const options = {
    scenarios: {
        spikeload: {
            executor: 'ramping-arrival-rate',
            //startTime: '45m', 
            startRate: 0,
            timeUnit: '1m', 
            stages: [
                { target: 0, duration: '1m' },
                { target: 1, duration: '1m' },
                { target: 0, duration: '7m' },
                { target: 20, duration: '1m' },
                { target: 1, duration: '3m' },
                { target: 0, duration: '1m' },
                { target: 5, duration: '1m' },
                { target: 1, duration: '4m' },
                { target: 2, duration: '1m' },
                { target: 0, duration: '1m' },
                { target: 1, duration: '2m' },
                { target: 0, duration: '1m' },
                { target: 1, duration: '1m' },
                { target: 0, duration: '1m' },
                { target: 2, duration: '1m' },
                { target: 0, duration: '1m' },
                { target: 1, duration: '1m' },
                { target: 15, duration: '2m' },
                { target: 1, duration: '1m' },
                { target: 3, duration: '1m' },
                { target: 1, duration: '1m' },
                { target: 2, duration: '2m' },
                { target: 0, duration: '2m' },
                { target: 2, duration: '1m' },
                { target: 1, duration: '1m' },
                { target: 0, duration: '1m' },
                { target: 1, duration: '3m' },
                { target: 20, duration: '5m' },
                { target: 1, duration: '1m' },
                { target: 3, duration: '1m' },
                { target: 1, duration: '2m' },
                { target: 0, duration: '3m' },
                { target: 2, duration: '1m' },
                { target: 1, duration: '1m' },
                { target: 0, duration: '3m' },
                { target: 2, duration: '1m' },
                { target: 0, duration: '1m' }
            ],
            preAllocatedVUs: 100,
            maxVUs: 300,
            tags: { test_type: 'spikeload', test_name: 'no-scaling' },
        },
    
    },
  }
  
  